name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: name
    attributes:
      label: Your Name
      placeholder: ex. Your Name
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New Feature
        - Improvement
        - Other
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Describe your request
    validations:
      required: true
